# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPuZvEioi8dcNJzkzHQu8TrBdNhP4xwD
"""


from diffusers import StableDiffusionPipeline
import torch
import matplotlib.pyplot as plt
device = "cuda" if torch.cuda.is_available() else "cpu"


# Load the pipeline
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)
pipe = pipe.to(device)  # Move to GPU

# Your custom prompt
prompt = input("Enter your prompt: ")

# Generate image
image = pipe(prompt).images[0]

# Save (optional)
image.save("output.png")

# Display using matplotlib
plt.imshow(image)
plt.axis("off")
plt.title("Your Waifu ❤️")
plt.show()